# Generated by Django 3.2.14 on 2022-08-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220802_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
